#!/bin/bash

cd $(dirname $0)/..

function die() {
  echo "$1"
  exit 1
}

MONGO_PORT=27017
which nc &>/dev/null && nc -vz localhost $MONGO_PORT 2>/dev/null || die "Can't find MongoDB on port $MONGO_PORT (using: nc -vz localhost $MONGO_PORT) - you may want to run 'docker run -p 27017:27017 -d mongo'"

SERVICE_PORT=9561

which sm &>/dev/null || die "Can't find Service Manager"

which nc &>/dev/null && nc -vz localhost $SERVICE_PORT 2>/dev/null && die "It appears the service is already running?"

sm --start ITSA_SUBSC_MIN "$@"
sleep 5

sm --stop INCOME_TAX_SUBSCRIPTION_FRONTEND
sleep 5

sbt "run $SERVICE_PORT -Dplay.http.router=testOnlyDoNotUseInAppConf.Routes"
   

 
  
